host = "http://localhost"
token =""
impostazione = "application/json"
Url1 = "/progettolaurea/public/api/authed/gen/pro/resp/"
Url2 = "/progettolaurea/public/api/authed/gen/pro/"
self = "self"
key = "key"