# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_test01(QWidget):
    def __init__(self, parent=None):
        super(Ui_test01, self).__init__(parent)
        test01 = self
        test01.setObjectName("test01")
        test01.resize(631, 427)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(test01.sizePolicy().hasHeightForWidth())
        test01.setSizePolicy(sizePolicy)
        test01.setBaseSize(QtCore.QSize(50, 0))
        self.textEdit = QtWidgets.QTextEdit(test01)
        self.textEdit.setGeometry(QtCore.QRect(0, 60, 631, 41))
        self.textEdit.setObjectName("textEdit")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(test01)
        self.commandLinkButton.setGeometry(QtCore.QRect(10, 110, 172, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton = QtWidgets.QPushButton(test01)
        self.pushButton.setGeometry(QtCore.QRect(300, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(test01)
        QtCore.QMetaObject.connectSlotsByName(test01)

    def retranslateUi(self, test01):
        _translate = QtCore.QCoreApplication.translate
        test01.setWindowTitle(_translate("test01", "test01"))
        self.commandLinkButton.setText(_translate("test01", "CommandLinkButton"))
        self.pushButton.setText(_translate("test01", "PushButton"))
