# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_TestClass(QWidget):
    
    def __init__(self, parent=None):
        super(Ui_TestClass, self).__init__(parent)
        TestClass = self
        TestClass.setObjectName("TestClass")
        TestClass.resize(717, 524)
        self.pushButton = QtWidgets.QPushButton(TestClass)
        self.pushButton.setGeometry(QtCore.QRect(130, 120, 151, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(TestClass)
        self.lineEdit.setGeometry(QtCore.QRect(300, 110, 171, 51))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(TestClass)
        QtCore.QMetaObject.connectSlotsByName(TestClass)

    def retranslateUi(self, TestClass):
        _translate = QtCore.QCoreApplication.translate
        TestClass.setWindowTitle(_translate("TestClass", "TestClass"))
        self.pushButton.setText(_translate("TestClass", "PushButton"))
