# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class Ui_UIwindow(QWidget):
    def __init__(self,provaCredenziali, parent=None):
        super(Ui_UIwindow, self).__init__(parent)
        self.credenziali = provaCredenziali
        print(self.credenziali)
        UIwindow = self
        UIwindow.setObjectName("UIwindow")
        UIwindow.resize(312, 362)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UIwindow.sizePolicy().hasHeightForWidth())
        UIwindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(UIwindow)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(UIwindow)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 102, 303))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        c = self.crealista()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(UIwindow)
        QtCore.QMetaObject.connectSlotsByName(UIwindow)

    def retranslateUi(self, UIwindow):
        _translate = QtCore.QCoreApplication.translate
        UIwindow.setWindowTitle(_translate("UIwindow", "UIwindow"))



    def crealista(self):
        b = []
        _translate = QtCore.QCoreApplication.translate
        for a in range(10,12):
            b.append(str(a))
            self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
            self.pushButton.setObjectName("pushButton"+str(a))
            self.gridLayout_2.addWidget(self.pushButton, a, 0, 1, 1)
            self.pushButton.setText(_translate("UIwindow", "PushButton"+str(a)))
        return b
