# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from typing import KeysView
from Dipendente.Controller.DipendenteC import DipendenteC
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
import copy

class Ui_VisualizzaAnagDip(QWidget):
    def __init__(self,CF, parent=None):
        super(Ui_VisualizzaAnagDip, self).__init__(parent)
        self.cf = CF
        VisualizzaAnagDip = self
        self.controller = DipendenteC()
        self._translate = QtCore.QCoreApplication.translate
        self.chiamata = self.controller.GetKey(self.cf)
        VisualizzaAnagDip.setObjectName("VisualizzaAnagDip")
        VisualizzaAnagDip.resize(800, 600)
        VisualizzaAnagDip.setWindowTitle(self._translate("VisualizzaAnagDip", "Visualizza Anagrafiche"))
        self.verticalLayout = QtWidgets.QVBoxLayout(VisualizzaAnagDip)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.AddLabelTitolo("Dettagli "+self.chiamata['nome_cognome'])
        
        self.gridLayout,self.scrollAreaWidgetContents = self.AddScrollArea(500)
        
        
        
        self.traduzione = {'CF':'codice fiscale',
        'nome_cognome':'nome e cognome',
        'tipo_dipendente':'tipo mansione',
        'importo_orario_feriale':'importo orario feriale',
        'importo_orario_regolare':'importo orario regolare',
        'importo_orario_straordinario':'importo orario straordinario',
        'IBAN':'IBAN',
        'username':'username',
        'data_di_nascita':'data di nascita'}

        #print(self.chiamata)
        #esclude elemento non desiderato per visualizzazione
        self.viewList = copy.deepcopy(self.chiamata)
        self.exclude = ['remember_token']
        for elem in self.exclude:
            self.viewList.pop(elem)

        
        self.count = 0
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        for a in self.viewList:
            self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
            self.label_2.setSizePolicy(sizePolicy)
            self.label_2.setMinimumSize(QtCore.QSize(0, 20))
            self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.label_2.setObjectName("label_2")
            self.gridLayout.addWidget(self.label_2, self.count, 0, 1, 1)
            self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
            self.label_3.setSizePolicy(sizePolicy)
            self.label_3.setMinimumSize(QtCore.QSize(0, 20))
            self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.label_3.setObjectName("label_3")
            self.gridLayout.addWidget(self.label_3, self.count, 1, 1, 1)
            
            self.label_2.setText(self._translate("VisualizzaAnagDip", "  "+str(self.traduzione[a])))
            self.label_3.setText(self._translate("VisualizzaAnagDip", "  "+str(self.chiamata[a])))
            self.count += 1

        QtCore.QMetaObject.connectSlotsByName(VisualizzaAnagDip)




    def AddLabelTitolo(self,text):
        
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label.setText(self._translate("ModificaDipAng", text))

    def AddScrollArea(self,min_size):
        scrollArea = QtWidgets.QScrollArea(self)
        scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        scrollArea.setWidgetResizable(True)
        scrollArea.setObjectName("scrollArea")
        scrollArea.setMinimumSize(QtCore.QSize(0, min_size))
        scrollAreaWidgetContents = QtWidgets.QWidget()
        scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 524))
        scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        gridLayout = QtWidgets.QGridLayout(scrollAreaWidgetContents)
        gridLayout.setObjectName("gridLayout")
        scrollArea.setWidget(scrollAreaWidgetContents)
        self.verticalLayout.addWidget(scrollArea)
        return (gridLayout,scrollAreaWidgetContents)