# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaLog(object):
    def setupUi(self, VistaLog):
        VistaLog.setObjectName("VistaLog")
        VistaLog.resize(755, 463)
        VistaLog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(VistaLog)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(VistaLog)
        self.scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 735, 443))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(290, 310, 121, 41))
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(180, 30, 361, 51))
        self.label.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(110, 150, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 240, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(110, 100, 391, 31))
        self.label_2.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(110, 200, 391, 31))
        self.label_3.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.label_3.setObjectName("label_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(VistaLog)
        QtCore.QMetaObject.connectSlotsByName(VistaLog)

    def retranslateUi(self, VistaLog):
        _translate = QtCore.QCoreApplication.translate
        VistaLog.setWindowTitle(_translate("VistaLog", "VistaLog"))
        self.pushButton.setText(_translate("VistaLog", "Invio"))
        self.label.setText(_translate("VistaLog", "Login"))
        self.label_2.setText(_translate("VistaLog", "UserName"))
        self.label_3.setText(_translate("VistaLog", "Password"))
