# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Ddt.Controller.DdtC import DdtC
from Ddt.View.VistaDDT import Ui_VistaDDT
from Ddt.View.VistaModificaDDT import Ui_VistaModificaDDT

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
from win32api import GetSystemMetrics # per prendere la risoluzione dello schermo computer

class Ui_ListaDDT(QWidget):
    def __init__(self, parent=None):
        super(Ui_ListaDDT, self).__init__(parent)
        self._translate = QtCore.QCoreApplication.translate
        ListaView = self
        self.controller = DdtC()
        self.key = 'Numero_ddt_aziendale'
        self.chiamata = self.controller.GetAll()
        ListaView.setObjectName("Lista Commesse")
        ListaView.resize(800, 600)
        ListaView.setWindowTitle(self._translate("Lista Commesse", "Lista Commesse"))
        self.verticalLayout = QtWidgets.QVBoxLayout(ListaView)
        self.verticalLayout.setObjectName("verticalLayout")

        self.sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.sizePolicy.setHorizontalStretch(0)
        self.sizePolicy.setVerticalStretch(0)

        self.AddLabelTitolo("Lista delle commesse")

        self.AddScrollArea()

        self.traduzione = {
        'Numero_ddt_aziendale':'Numero DDT',
        'data':'data',
        'entrata':'fattura'
        }

        self.listAttr = [
            {'nome':'Numero_ddt_aziendale','width':80},
            {'nome':'data','width':100},
            {'nome':'entrata','width':200},
        ]
        #le dimensioni delle colonne

        sizes = [x['width'] for x in self.listAttr]
        # se contabile o non contabile
        listcontabile = [x['contabile'] for x in self.chiamata] 

        total = sum(sizes)+500
        height = total*0.75-100 if((total*0.75)>GetSystemMetrics(1)-100) else GetSystemMetrics(1)-100
        ListaView.resize(total,height)
        
        #DDT
        for attr in range(len(self.listAttr)):
            #Aggiunge l'intestazione della tabella
            self.AddTableHeader(self.traduzione[self.listAttr[attr]['nome']],attr,self.listAttr[attr]['width'])
        

        for a in range(0,len(self.chiamata)):
            if( listcontabile[a] == None):
                
                self.AddTableContent(0,a+1,str(self.chiamata[a]['Numero_ddt_aziendale']),self.listAttr[0]['width'],"background-color: rgb(123, 123, 123);")
                self.AddTableContent(1,a+1,str(self.chiamata[a]['non_contabile']['data']),self.listAttr[1]['width'],"background-color: rgb(123, 123, 123);")
                self.AddTableContent(2,a+1,"non contabile",self.listAttr[2]['width'],"background-color: rgb(123, 123, 123);")
            else:
                self.AddTableContent(0,a+1,str(self.chiamata[a]['Numero_ddt_aziendale']),self.listAttr[0]['width'])
                self.AddTableContent(1,a+1,str(self.chiamata[a]['contabile']['data']),self.listAttr[1]['width'])
                self.AddTableContent(2,a+1,str(self.chiamata[a]['contabile']['entrata']),self.listAttr[2]['width'])
    

        #Aggiunge pulsante delle operazioni
        self.OperationButtons=[
            {
                "name":"Visualizza Elemento",
                "StyleSheet":"background-color: rgb(0, 255, 0);\n color: rgb(255, 255, 255);",
                "function":self.Visualizza
            },
            {
                "name":"Cancella Elemento",
                "StyleSheet":"background-color: rgb(255, 0, 0);\n color: rgb(255, 255, 255);",
                "function":self.deleteConfirm
            },
            {
                "name":"Modifica Elemento",
                "StyleSheet":"background-color: rgb(0, 0, 255);\n color: rgb(255, 255, 255);",
                "function":self.Modify
            }
        ]

        #TODO add different button in base of type
        X_offset = len(self.listAttr)
        for i in range(0,len(self.OperationButtons)):
            for a in range(0,len(self.chiamata)):
                #print(i)
                self.AddOperationButton(X_offset+i,a,self.OperationButtons[i],lambda state,b=a,c=i: self.OperationButtons[c]["function"](self.chiamata[b],listcontabile[b]))
    
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        QtCore.QMetaObject.connectSlotsByName(ListaView)

    #chiamata alla funzione per la cancellazione di un elemento
    def deleteConfirm(self,elem,contabile):

        msg = QMessageBox()
        msg.setWindowTitle('Conferma')
        msg.setText('sei sicuro di voler cancellare il DDT numero'+str(elem['Numero_ddt_aziendale']) + '?')
        msg.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        okButton = msg.button(QMessageBox.Yes)
        noButton = msg.button(QMessageBox.No)
        okButton.setText('si')
        retval = msg.exec_()
        if(msg.clickedButton() == okButton):
            print('cancellazione confermata')
            postbody = {'ddt':elem[self.key]}
            if(contabile != None):
                res = self.controller.ContaBileDelete(postbody)
            else:
                res = self.controller.NonContabileDelete(postbody)

            print(res)
            self.RefreshLista = Ui_ListaDDT()
            self.RefreshLista.show()
            self.close()
        else:
            print('cancellazione annullata')

    #Viene chiamata la funzione per visualizzare i dettagli di quell'elemento
    def Visualizza(self,elem,tipo):
        print(elem)
        print(tipo)
        self.Dettaglio = Ui_VistaDDT(str(elem[self.key]),contabile=tipo)
        self.Dettaglio.show()

    def Modify(self,elem,tipo):
        print (elem[self.key])
        self.modificaview = Ui_VistaModificaDDT(elem[self.key],contabile=tipo)
        self.modificaview.show()
        self.close()

    #Viene settata l'intestazione della finestra
    def AddTableHeader(self,text,pos,width):
        self.header1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sizePolicy.setHeightForWidth(self.header1.sizePolicy().hasHeightForWidth())
        self.header1.setSizePolicy(self.sizePolicy)
        self.header1.setMinimumSize(QtCore.QSize(width, 30))
        self.header1.setObjectName("header1")
        self.header1.setText(self._translate("ListaView",text))
        self.gridLayout.addWidget(self.header1, 0, pos, 1, 1)
        self.gridLayout.setRowStretch (0, 0)
    
    #Questa funzione aggiunge le label alla finestra
    def AddTableContent(self,x,y,content,width,stylesheet = "background-color: rgb(255, 255, 255);"):
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(self.sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(width, 30))
        self.label_3.setMaximumSize(QtCore.QSize(width*3, 30))
        self.label_3.setStyleSheet(stylesheet)
        self.label_3.setObjectName("label_3")
        self.label_3.setText(self._translate("ListaView","   "+ content))
        self.gridLayout.addWidget(self.label_3, y, x, 1, 1)
        self.gridLayout.setRowStretch (y, 0)
        self.gridLayout.setRowStretch (y+1, 1)

    #Questa funzione aggiunge un bottone a cui viene collegata una particolare funzione, da attivare quando 
    # il bottone viene premuto
    def AddOperationButton(self,x,y,buttonDict,function):
        OperationButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        OperationButton.setStyleSheet(buttonDict["StyleSheet"])
        OperationButton.setObjectName("OperationButton")
        OperationButton.setText(self._translate("ListaView", buttonDict["name"]))        
        OperationButton.clicked.connect(function)
        self.gridLayout.addWidget(OperationButton, y+1, x, 1, 1)
        return OperationButton
    
    #Questa funzione aggiunge una scroll area
    def AddScrollArea(self):
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")

    # In questa funzione viene impostata la label che si trova sopra la lista
    def AddLabelTitolo(self,text):
        self.label = QtWidgets.QLabel(self)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label.setText(self._translate("ModificaDipAng", text))