# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Magazzino.View.MagazzinoV import Ui_ListaMagazzino
from Aggiornamento.View.AggiornamentoV import Ui_ListaAggiornamenti
from VistaFinanziari.VistaFinanziari import VistaFinanziari
from VistaAnagrafica.VistaAnagrafica import VistaAnagrafica
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget


class Ui_VistaStrategiche(QWidget):
    def __init__(self, parent=None,fakeparent=None):
        super(Ui_VistaStrategiche, self).__init__(parent)
        _translate = QtCore.QCoreApplication.translate
        self.fakeparent = fakeparent
        VistaStrategiche = self
        VistaStrategiche.setObjectName("VistaStrategiche")
        VistaStrategiche.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(VistaStrategiche)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(VistaStrategiche)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 580))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText(_translate("VistaStrategiche", "Lista aggiornamenti"))
        self.pushButton.clicked.connect(self.GoListaAggiornamenti)
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        QtCore.QMetaObject.connectSlotsByName(VistaStrategiche)    
        VistaStrategiche.setWindowTitle(_translate("VistaStrategiche", "VistaStrategiche"))
        self.label.setText(_translate("VistaStrategiche", "Welcome Home"))
        
        self.pushButton_2.setText(_translate("VistaStrategiche", "Articoli del magazzino"))
        self.pushButton_3.setText(_translate("VistaStrategiche", "Lista dati finanziari"))
        self.pushButton_2.clicked.connect(self.GoListaMagazzino)
        self.pushButton_3.clicked.connect(self.GoVistaFinanziari)

    def closeEvent(self, event):
        if(self.handClose ==0):
            self.handClose = 1
        else:
            self.fakeparent.show()
        event.accept()

    def GoListaMagazzino(self):
        self.magazzino = Ui_ListaMagazzino()
        self.magazzino.show()
        self.close()

    def GoListaAggiornamenti(self):
        self.Anagrafica = Ui_ListaAggiornamenti()
        self.Anagrafica.show()
        self.handClose = 0
        self.close()
    
    def GoVistaFinanziari(self):
        self.Finanziari = VistaFinanziari()
        self.Finanziari.show()
        self.handClose = 0
        self.close()
