# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VistaAnagrafica.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget

from Dipendente.View.VistaListaDipendenti import Ui_ListaDipendenti
from ListinoPrezzi.View.VistaListaListinoPrezzi import Ui_ListaListinoPrezzi
from Cliente.View.VistaListaCliente import Ui_ListaCliente
from Dipendente.View.VistaInserisciDipendente import Ui_InserisciDip


class VistaAnagrafica(QWidget):
    def __init__(self, parent=None):
        super(VistaAnagrafica, self).__init__(parent)
        _translate = QtCore.QCoreApplication.translate
        HomeClass = self
        HomeClass.setObjectName("VistaAnagrafica")
        HomeClass.resize(756, 585)
        self.verticalLayout = QtWidgets.QVBoxLayout(HomeClass)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(HomeClass)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 200))
        self.scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 732, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListaClienteButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ListaClienteButton.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListaClienteButton.setFont(font)
        self.ListaClienteButton.setObjectName("ListaClienteButton")
        self.horizontalLayout.addWidget(self.ListaClienteButton)
        self.AddClienteButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AddClienteButton.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddClienteButton.setFont(font)
        self.AddClienteButton.setObjectName("AddClienteButton")
        self.horizontalLayout.addWidget(self.AddClienteButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n""color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ListaPrezzo = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ListaPrezzo.setMinimumSize(QtCore.QSize(300, 50))
        self.ListaPrezzo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListaPrezzo.setFont(font)
        self.ListaPrezzo.setObjectName("ListaPrezzo")
        self.horizontalLayout_2.addWidget(self.ListaPrezzo)
        self.AddListaPrezzo = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AddListaPrezzo.setMinimumSize(QtCore.QSize(300, 50))
        self.AddListaPrezzo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddListaPrezzo.setFont(font)
        self.AddListaPrezzo.setObjectName("AddListaPrezzo")
        self.horizontalLayout_2.addWidget(self.AddListaPrezzo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setContentsMargins(20, -1, 20, -1)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AddDipendenteButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AddDipendenteButton.setMinimumSize(QtCore.QSize(300, 50))
        self.AddDipendenteButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddDipendenteButton.setFont(font)
        self.AddDipendenteButton.setObjectName("AddDipendenteButton")
        self.AddDipendenteButton.clicked.connect(self.Go_InserisciDipendente)
        self.gridLayout_2.addWidget(self.AddDipendenteButton, 1, 2, 1, 1)
        self.ListaDipendenti = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ListaDipendenti.setMinimumSize(QtCore.QSize(300, 50))
        self.ListaDipendenti.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListaDipendenti.setFont(font)
        self.ListaDipendenti.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.ListaDipendenti, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ListaMacchine = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ListaMacchine.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ListaMacchine.setFont(font)
        self.ListaMacchine.setObjectName("ListaMacchine")
        self.horizontalLayout_3.addWidget(self.ListaMacchine)
        self.AddMacchina = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.AddMacchina.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddMacchina.setFont(font)
        self.AddMacchina.setObjectName("AddMacchina")
        self.horizontalLayout_3.addWidget(self.AddMacchina)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        QtCore.QMetaObject.connectSlotsByName(HomeClass)

        _translate = QtCore.QCoreApplication.translate
        HomeClass.setWindowTitle(_translate("HomeClass", "HomeClass"))
        self.label.setText(_translate("HomeClass", "Vista Anagrafica"))

        self.label_2.setText(_translate("HomeClass", "Dipendente"))
        self.ListaDipendenti.setText(_translate("HomeClass", "Lista dipendenti"))
        self.ListaDipendenti.clicked.connect(self.Go_ListaDipendenti)
        self.AddDipendenteButton.setText(_translate("HomeClass", "Aggiunge un dipendente"))
        self.ListaDipendenti.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.AddDipendenteButton.setStyleSheet("background-color: rgb(85, 255, 255);")


        self.label_3.setText(_translate("HomeClass", "Clienti"))
        self.ListaClienteButton.setText(_translate("HomeClass", "Lista cliente"))
        self.ListaClienteButton.clicked.connect(self.Go_ListinaClienti)
        self.AddClienteButton.setText(_translate("HomeClass", "Aggiunge un cliente"))
        self.ListaClienteButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.AddClienteButton.setStyleSheet("background-color: rgb(85, 255, 255);")

        self.label_4.setText(_translate("HomeClass", "Listino Prezzi"))
        self.ListaPrezzo.setText(_translate("HomeClass", "Lista listino prezzi"))
        self.ListaPrezzo.clicked.connect(self.Go_ListinoPrezzi)
        self.AddListaPrezzo.setText(_translate("HomeClass", "Aggiunge un listono prezzi"))
        self.ListaPrezzo.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.AddListaPrezzo.setStyleSheet("background-color: rgb(85, 255, 255);")


        self.label_5.setText(_translate("HomeClass", "Macchinari"))  
        self.ListaMacchine.setText(_translate("HomeClass", "Lista macchinari"))
        self.AddMacchina.setText(_translate("HomeClass", "Aggiunge un macchinario"))
        self.ListaMacchine.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.AddMacchina.setStyleSheet("background-color: rgb(85, 255, 255);")
        

    def Go_ListaDipendenti(self):
        self.ListaDipendeti = Ui_ListaDipendenti()
        self.ListaDipendeti.show()

    def Go_ListinoPrezzi(self):
        self.ListinoPrezzi = Ui_ListaListinoPrezzi()
        self.ListinoPrezzi.show()

    def Go_ListinaClienti(self):
        self.ListaClienti = Ui_ListaCliente()
        self.ListaClienti.show()

    def Go_InserisciDipendente(self):
        self.InserisciDipendente = Ui_InserisciDip()
        self.InserisciDipendente.show()