# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from typing import KeysView
from Cliente.Controller.ClienteC import ClienteC
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QWidget
import copy

class Ui_Cliente(QWidget):
    def __init__(self,CF, parent=None):
        super(Ui_Cliente, self).__init__(parent)
        _translate = QtCore.QCoreApplication.translate
        
        
        self.cf = CF
        VisualizzaAnagDip = self
        self.controller = ClienteC()
        self.chiamata = self.controller.GetKey(self.cf)
        VisualizzaAnagDip.setObjectName("VisualizzaAnagDip")
        VisualizzaAnagDip.resize(800, 600)
        VisualizzaAnagDip.setWindowTitle(_translate("VisualizzaAnagDip", "VisualizzaAnagDip"))
        self.verticalLayout = QtWidgets.QVBoxLayout(VisualizzaAnagDip)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(VisualizzaAnagDip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.label.setText(_translate("VisualizzaAnagDip", "<html><head/><body><p align=\"center\">Dettagli</p></body></html>"))
        self.scrollArea = QtWidgets.QScrollArea(VisualizzaAnagDip)
        self.scrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        

        self.traduzione = {'PIVA':'partita iva',
        'nome_azienda':'nome dell\'azienda',
        'CAP':'CAP',
        'email':'posta elettronica',
        'sito_web':'sito dell\'azienda',
        'citta':'citta\'',
        'via':'via',
        'nc':'numero civico',
        'telefono':'numero telefonico',
        'numero':'numero'
        }
        
        self.commessa = copy.deepcopy(self.chiamata['commessa'])
        
        #print(self.chiamata)
        #esclude elemento non desiderato per visualizzazione
        self.viewList = copy.deepcopy(self.chiamata)

        self.exclude = ['commessa','telefono']
        for elem in self.exclude:
            self.viewList.pop(elem)


        self.count = 0
        print(self.viewList)

        for a in self.viewList:
            self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
            self.label_2.setSizePolicy(sizePolicy)
            self.label_2.setMinimumSize(QtCore.QSize(0, 20))
            self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.label_2.setObjectName("label_2")
            self.gridLayout.addWidget(self.label_2, self.count, 0, 1, 1)
            self.label_2.setText(_translate("VisualizzaAnagDip", "  "+str(self.traduzione[a])))

            
            self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
            sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
            self.label_3.setSizePolicy(sizePolicy)
            self.label_3.setMinimumSize(QtCore.QSize(0, 20))
            self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
            self.label_3.setObjectName("label_3")
            self.gridLayout.addWidget(self.label_3, self.count, 1, 1, 1)
            _translate = QtCore.QCoreApplication.translate
            
            self.label_3.setText(_translate("VisualizzaAnagDip", "  "+str(self.chiamata[a])))
            self.count += 1

        #Sezione del telefono
        self.telefono = copy.deepcopy(self.chiamata['telefono'])
        self.telefono_attr = ['numero']
        if(len(self.telefono)>0):
        
            self.TelefonoLabel = QtWidgets.QLabel(VisualizzaAnagDip)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
            sizePolicy.setHorizontalStretch(0)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.TelefonoLabel.sizePolicy().hasHeightForWidth())
            self.TelefonoLabel.setSizePolicy(sizePolicy)
            self.TelefonoLabel.setMinimumSize(QtCore.QSize(250, 50))
            font = QtGui.QFont()
            font.setPointSize(20)
            self.TelefonoLabel.setFont(font)
            self.TelefonoLabel.setObjectName("label")
            self.verticalLayout.addWidget(self.TelefonoLabel, 0, QtCore.Qt.AlignHCenter)
            self.TelefonoLabel.setText(_translate("VisualizzaAnagDip", "<html><head/><body><p align=\"center\">Telefono</p></body></html>"))
            self.TelefonoscrollArea = QtWidgets.QScrollArea(VisualizzaAnagDip)
            self.TelefonoscrollArea.setStyleSheet("background-color: rgb(109, 109, 109);")
            self.TelefonoscrollArea.setWidgetResizable(True)
            self.TelefonoscrollArea.setObjectName("TelefonoscrollArea")
            self.scrollAreaWidgetContents = QtWidgets.QWidget()
            self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 524))
            self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
            self.TelefonoGridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
            self.TelefonoGridLayout.setObjectName("TelefonoGridLayout")
            self.TelefonoscrollArea.setWidget(self.scrollAreaWidgetContents)
            self.verticalLayout.addWidget(self.TelefonoscrollArea)


            for a in range(len(self.telefono_attr)):
                self.label_headTelefono = QtWidgets.QLabel(self.scrollAreaWidgetContents)
                sizePolicy.setHeightForWidth(self.label_headTelefono.sizePolicy().hasHeightForWidth())
                self.label_headTelefono.setSizePolicy(sizePolicy)
                self.label_headTelefono.setMinimumSize(QtCore.QSize(0, 20))
                self.label_headTelefono.setObjectName("label_headTelefono")
                self.TelefonoGridLayout.addWidget(self.label_headTelefono, 0, a, 1, 1)
                self.label_headTelefono.setText(self.traduzione[self.telefono_attr[a]])

            
            for a in range(len(self.telefono_attr)):
                self.count = 1
                for numero in self.telefono:
                    self.label_numero = QtWidgets.QLabel(self.scrollAreaWidgetContents)
                    sizePolicy.setHeightForWidth(self.label_numero.sizePolicy().hasHeightForWidth())
                    self.label_numero.setSizePolicy(sizePolicy)
                    self.label_numero.setMinimumSize(QtCore.QSize(0, 20))
                    self.label_numero.setStyleSheet("background-color: rgb(255, 255, 255);")
                    self.label_numero.setObjectName("label_numero")
                    self.TelefonoGridLayout.addWidget(self.label_numero, self.count, a, 1, 1)
                    self.label_numero.setText(_translate("VisualizzaAnagDip", "  "+str(numero[self.telefono_attr[a]])))
                    self.count += 1  

              

        QtCore.QMetaObject.connectSlotsByName(VisualizzaAnagDip)

        
    